### PR TITLE
The nccopy client  tutorial

### PR DESCRIPTION
**Pull request by ndp-opendap**
I think to review this PR one should examine the two primary files as rendered in our GitHub pages because the reading is easier and I am also editing for presentation format which one can only see in the rendered pages.

- https://opendap.github.io/documentation/tutorials/nccopy_tutorial.html
- https://opendap.github.io/documentation/tutorials/ClientAuthentication.html

Thanks for reading!

### CODE REVIEW

**Review by jgallagher59701 — CHANGES_REQUESTED** [review]
The Authentication is great.

In the authentication doc, sections 9.1 and 10.1 refer to URS - that should be changed.

I wonder if organizing the by auth service and then client might not make the similarities between the clients easier to see? A thought... 

The tutorial is great, too.

In the nccopy tutorial, I think "This tutorial assumes that the reader has a good grasp of bash shell programming." could be changed to 'basic grasp.' The scripts are pretty simple, but it's really a minor point.

Missing ")": (and often can be acquired from a package manager such as brew/yum/dnf/apt-get. 

I don't have these configured, but they work for me with EDL. I do have the Hyrax configured. -->

[If you have not configured EDL authentication for nccopy and ncdump yet, please go do that now!](https://opendap.github.io/documentation/tutorials/ClientAuthentication.html)

**Comment by dh-opendap** [comment]
Read both tutorials, they seem fine.  Didn't perform all the variants discussed in the ClientAuthentication tutorial but the initial (IMO primary) examples I did, or have in the past as my Earthdata Login account matches this information.

Only comment I have on the nccopy tutorial is the following statement (lines 46-48, something like that):

"Since the authentication setup is complex, yet similar for many clients. We have covered it in a separate document."

I think that should be one sentence.

"Since the authentication setup is complex, yet similar for many clients, we have covered it in a separate document."

Otherwise everything seems good to me.

**Review by dh-opendap — APPROVED** [review]
Good, would recommend a small grammatical fix on the nccopy tutorial, lines 46,47, otherwise I don't have any specific change requests.  Have noted James change requests to the ClientAuthentication tutorial.

**Review by jgallagher59701 — APPROVED** [review]
Merge! Thanks.

**Pull request merged**
